"""The ``astro-mine worlds`` CLI — validate a WorldSpec, publish a built bundle.

A stdlib-``argparse`` front door (no CLI-framework runtime dependency), mirroring the ``fleet``
CLI. Three subcommands:

- ``validate`` — check one or more authored ``WorldSpec`` documents against the model: schema,
  the extent rule, and the explicit-CRS gate that rejects an implicit Earth datum on a non-Earth
  body. The dispatch is importable so the umbrella's federated ``astro-mine validate``
  (RFC-0011 §6) routes into *this* checker rather than reimplementing it — one answer to "is this
  valid", whichever command a user types.
- ``schema`` — print the published ``WorldSpec`` JSON Schema, so a consumer that cannot import the
  Pydantic model still has the contract (worlds.md §11). It is also how the shipped copy is
  regenerated when the model moves.
- ``publish`` — publish a built world-bundle directory to a local OCI-layout Hub registry (or a
  remote one, e.g. ``ghcr.io/astro-mine``) as a signed, content-addressed ``world`` artifact (cosign
  ECDSA-P256 + SLSA + SBOM), emitting the Core ``world_provider`` manifest so Sim/Bench resolve the
  world by digest.

The signing key ``publish --key`` needs is generated by ``astro-mine hub keygen`` — the one
signing-key command (this CLI no longer carries its own). ``astro-mine hub`` (the ``[hub]`` extra)
is imported lazily inside the handler so the base package stays dependency-light and offline.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

from astro_mine.worlds import __version__

__all__ = ["main"]


def _cmd_validate(args: argparse.Namespace) -> int:
    """Validate authored WorldSpec documents; return 0 if every one is valid.

    Named ``_cmd_validate`` rather than ``_validate`` to match the handler convention the sibling
    CLIs use, and importable because the umbrella's federated `astro-mine validate` calls it
    directly — the same checker, reached by another road, so the two surfaces cannot disagree about
    what is valid (RFC-0011 §6).

    Every path is checked even after one fails: a user fixing an authoring mistake wants the whole
    list, not the first line of it.
    """
    import json as _json

    from astro_mine.worlds.spec import WorldSpec

    failures: list[dict[str, str]] = []
    passes: list[dict[str, str]] = []
    for path in args.path:
        try:
            spec = WorldSpec.from_yaml(path)
        except Exception as exc:
            # Any authoring error — unreadable file, malformed YAML, schema violation, the
            # explicit-CRS gate — is the user's to see and fix, reported the same way. A traceback
            # here would bury the one line that says what is wrong with their document.
            failures.append({"path": str(path), "error": _one_line(exc)})
        else:
            passes.append({"path": str(path), "world_id": spec.world_id, "hash": spec.spec_hash})

    if getattr(args, "json", False):
        print(
            _json.dumps({"ok": not failures, "valid": passes, "invalid": failures}, sort_keys=True)
        )
    else:
        for entry in passes:
            print(f"OK  {entry['path']}: valid WorldSpec {entry['world_id']} ({entry['hash']})")
        for failure in failures:
            print(f"FAIL {failure['path']}: {failure['error']}", file=sys.stderr)
    return 1 if failures else 0


def _cmd_schema(args: argparse.Namespace) -> int:
    """Print the published ``WorldSpec`` JSON Schema.

    The schema is a **contract**, not an implementation detail: a non-Python consumer — View
    ingesting a bundle, a CI gate checking an authored document — cannot import the Pydantic model,
    so the schema has to be reachable without this package's Python. Printing the *shipped* bytes
    rather than regenerating them means what a user pipes to a file is exactly what the wheel
    publishes under its ``$id``.

    It is also how the shipped copy is regenerated when the model moves:
    ``astro-mine worlds schema > src/astro_mine/worlds/spec/schema/worldspec.schema.json``.
    """
    from astro_mine.worlds.spec import published_json_schema_text

    del args
    print(published_json_schema_text().rstrip("\n"))
    return 0


def _one_line(exc: Exception) -> str:
    """Collapse a pydantic ValidationError's multi-line report into one readable line."""
    text = " ".join(str(exc).split())
    return text if len(text) <= 300 else f"{text[:297]}..."


def _publish(args: argparse.Namespace) -> int:
    """Publish a built bundle directory; print the ``name:version`` reference and digest."""
    from astro_mine.hub.registry import open_registry
    from astro_mine.worlds.spec import WorldBundle, publish_world_bundle

    bundle = WorldBundle.load(args.bundle)
    # `open_registry` dispatches on the string: a filesystem path → the local OCI-layout store
    # (unchanged), a registry URL like `ghcr.io/astro-mine` → the remote OCI Distribution client.
    registry = open_registry(args.registry)
    private_key_pem = Path(args.key).read_bytes()
    name = args.name or bundle.world_id
    version = args.version or bundle.spec.version
    artifact = publish_world_bundle(
        bundle, registry, private_key_pem=private_key_pem, name=name, version=version
    )
    print(f"published {artifact.reference} -> {artifact.digest}")
    return 0


def _add_arguments(parser: argparse.ArgumentParser) -> None:
    parser.description = (
        "Astro-Mine Worlds toolchain."
    )
    parser.add_argument("--version", action="version", version=f"astro-mine worlds {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)

    validate = sub.add_parser("validate", help="Validate one or more authored WorldSpec documents.")
    validate.add_argument("path", nargs="+", help="Path to a WorldSpec YAML document.")
    validate.add_argument("--json", action="store_true", help="Machine-readable output.")
    validate.set_defaults(func=_cmd_validate)

    schema = sub.add_parser(
        "schema", help="Print the published WorldSpec JSON Schema (by its $id)."
    )
    schema.set_defaults(func=_cmd_schema)

    publish = sub.add_parser(
        "publish", help="Publish a built world bundle to a local OCI-layout Hub registry."
    )
    publish.add_argument("bundle", help="Path to a built world-bundle directory (has world.json).")
    publish.add_argument(
        "--registry",
        required=True,
        help="Local OCI-layout registry path, or a remote registry URL (e.g. ghcr.io/astro-mine).",
    )
    publish.add_argument("--key", required=True, help="Cosign ECDSA-P256 private key (PEM) path.")
    publish.add_argument("--name", default=None, help="Artifact name (default: the world_id).")
    publish.add_argument("--version", default=None, help="Artifact version (default: spec ver).")
    publish.set_defaults(func=_publish)

class _Command:
    """`astro-mine worlds <verb>` — author and publish world bundles."""

    name = "worlds"
    help = "author and publish world bundles"

    def add_arguments(self, parser: argparse.ArgumentParser) -> None:
        _add_arguments(parser)

    def run(self, args: argparse.Namespace) -> int:
        return int(args.func(args))


command = _Command()




#: The root properties ``WorldSpec`` declares with no default — the claim key for
#: `astro-mine validate`. Kept as data so the rule and the model cannot drift apart silently:
#: a test derives this same set from the model and compares, so adding a required field to
#: ``WorldSpec`` without revisiting the claim fails loudly.
REQUIRED_ROOT: frozenset[str] = frozenset({"world_id", "crs", "region", "source_dem"})


class _WorldsValidator:
    """Worlds's half of the federated `astro-mine validate` (RFC-0011 §6)."""

    name = "worlds"

    def claims(self, path: str) -> str | None:
        """Return ``"world_spec"`` if ``path`` is a WorldSpec, else ``None``.

        Cheap and total: the umbrella asks every installed validator about every file, so a
        document that is Core's or Guard's must come back ``None`` rather than raise — at claim
        time nobody owns the file yet, and raising would turn another component's malformed
        document into a Worlds traceback. A file that *is* Worlds's but malformed is claimed here
        and then reported properly by the real checker.
        """
        import yaml

        try:
            with open(path, encoding="utf-8") as handle:
                document = yaml.safe_load(handle)
        except (OSError, yaml.YAMLError):
            return None
        if isinstance(document, dict) and document.keys() >= REQUIRED_ROOT:
            return "world_spec"
        return None

    def validate(self, paths: Sequence[str], *, as_json: bool) -> int:
        """Run the same checker `astro-mine-worlds validate` runs — not a second implementation."""
        return int(_cmd_validate(argparse.Namespace(path=list(paths), json=as_json)))


validator = _WorldsValidator()
